name: auto link pull request
description: link  pull request to related issue based on issue title and pull request branch
author: 'ali salemi'

runs:
  using: 'node12'
  main: 'dist/index.js'

inputs:
  github_token:
    required: true
    description: github token
